[target.x86_64-unknown-linux-musl]
pre-build = [
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
    "apt-get update && apt-get install -y nodejs"
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
    "apt-get update && apt-get install -y nodejs"
]

[aarch64-unknown-linux-gnu]
pre-build = [
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
    "apt-get update && apt-get install -y nodejs"
]

[armv7-unknown-linux-gnueabihf]
pre-build = [
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
    "apt-get update && apt-get install -y nodejs"
]
