// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/reaper47/heavy-metal-notifier/internal/templates"
)

func layout(data templates.Data) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.PageTitle != "" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<title>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.PageTitle)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `base.templ`, Line: 11, Col: 27}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" | Heavy Metal Releases</title>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<title>Heavy Metal Releases</title>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<meta charset=\"UTF-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"description\" content=\"Be notified of new heavy metal album releases.\"><meta name=\"keywords\" content=\"heavy metal, album releases, satan, automation\"><link rel=\"canonical\" href=\"https://metal.musicavis.ca/\"><link rel=\"icon\" href=\"/static/favicon.png\" type=\"image/x-icon\"><link rel=\"stylesheet\" href=\"/static/css/tailwind.css\"></head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.ShowNav {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav><div class=\"container mx-auto px-6 py-2 flex justify-between items-center\"><a class=\"font-bold lg:text-3xl\" style=\"display: ruby\" href=\"/\"><img src=\"/static/img/logo-64x64.png\" alt=\"logo\" class=\"w-[2.5rem]\"> Heavy Metal Releases</a><div class=\"flex flex-col relative\"><div id=\"menu-icon\" class=\"block lg:hidden\"><button class=\"flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-800 hover:border-teal-500 appearance-none focus:outline-none\"><svg class=\"fill-current h-3 w-3\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\"><title>Menu</title><path d=\"M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z\"></path></svg></button></div><div id=\"menu\" class=\"hidden absolute top-[2.45rem]  bg-white right-[-1.5rem] w-[100vw] text-center lg:block lg:relative lg:w-auto lg:bg-transparent lg:top-0\"><ul class=\"lg:flex\"><li class=\"py-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 = []any{"px-4", templ.KV("font-bold", data.IsHomePage), templ.KV("hover:text-gray-800", !data.IsHomePage)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var3...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ.CSSClasses(templ_7745c5c3_Var3).String()))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" href=\"/\">Home</a></li><li class=\"py-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 = []any{"px-4", templ.KV("font-bold", data.IsAboutPage), templ.KV("hover:text-gray-800", !data.IsHomePage)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var4...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ.CSSClasses(templ_7745c5c3_Var4).String()))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" href=\"/about\">About</a></li><li class=\"py-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 = []any{"px-4", templ.KV("font-bold", data.IsContactPage), templ.KV("hover:text-gray-800", !data.IsHomePage)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var5...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ.CSSClasses(templ_7745c5c3_Var5).String()))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" href=\"/contact\">Contact</a></li></ul></div></div></div></nav>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body class=\"h-screen font-sans anti-aliased\"><main class=\"grid h-full w-full md:grid-cols-12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.ShowNav {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"col-span-12 bg-gray-100\"><div class=\"container mx-auto pt-10 pb-6\"><div class=\"flex flex-wrap\"><div class=\"w-full md:w-1/3 text-center md:text-center\"><h5 class=\"uppercase mb-6 font-bold\">Links</h5><ul class=\"mb-4\"><li class=\"mt-2\"><a href=\"/contact\" class=\"hover:underline text-gray-600 hover:text-orange-500\">Support</a></li><li class=\"mt-2\"><a href=\"/sitemap\" class=\"hover:underline text-gray-600 hover:text-orange-500\">Sitemap</a></li></ul></div><div class=\"w-full md:w-1/3 text-center md:text-center\"><h5 class=\"uppercase mb-6 font-bold\">Legal</h5><ul class=\"mb-4\"><li class=\"mt-2\"><a href=\"/tos\" class=\"hover:underline text-gray-600 hover:text-orange-500\">Terms of Service</a></li><li class=\"mt-2\"><a href=\"/privacy\" class=\"hover:underline text-gray-600 hover:text-orange-500\">Privacy Policy</a></li></ul></div><div class=\"w-full md:w-1/3 text-center md:text-center\"><h5 class=\"uppercase mb-6 font-bold\">Service</h5><ul class=\"mb-4\"><li class=\"mt-2\"><a href=\"/about\" class=\"hover:underline text-gray-600 hover:text-orange-500\">About Us</a></li><li class=\"mt-2\"><a href=\"/contact\" class=\"hover:underline text-gray-600 hover:text-orange-500\">Contact</a></li></ul></div></div></div></footer>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</main><script defer>\n        const menu = document.querySelector('#menu');\n        const menuIcon = document.querySelector('#menu-icon');\n\n        if (menu) {\n            menuIcon.addEventListener('mousedown', () => {\n                menu.classList.toggle('hidden');\n            });\n\n            document.addEventListener('click', (event) => {\n                if (!menu.contains(event.target) && !menuIcon.contains(event.target)) {\n                    menu.classList.add('hidden');\n                }\n            });\n        }\n    </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
