// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/reaper47/heavy-metal-notifier/internal/templates"
)

func ContactPage(data templates.Data) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"col-span-12 py-20\" style=\"background: linear-gradient(90deg, #D73737 0%, #3D3D3D 100%)\"></section><section class=\"col-span-12 container mx-auto px-6 p-10\"><div class=\"flex items-center flex-wrap mb-20\"><div class=\"w-full md:w-1/2\"><h4 class=\"text-3xl text-gray-800 font-bold mb-3\">Contact us</h4><p class=\"text-gray-600 mb-4\">To address any inquiries, please send a message to us directly from the form below.</p><form class=\"w-full md:w-3/4 bg-white p-6 rounded-lg shadow-md mb-8\" method=\"post\" action=\"/contact\"><div class=\"mb-4\"><label class=\"block font-bold mb-2\" for=\"email\">Email</label> <input class=\"border border-gray-400 p-2 w-full\" type=\"email\" id=\"email\" name=\"email\" placeholder=\"your@email.com\" required></div><div class=\"mb-4\"><label class=\"block font-bold mb-2\" for=\"message\">Message</label> <textarea class=\"border border-gray-400 p-2 w-full h-32\" id=\"message\" name=\"message\" placeholder=\"Hello Metal Releases, I have something to say.\" required></textarea></div><div class=\"text-right\"><button class=\"w-full bg-indigo-500 text-white py-2 px-4 rounded-full hover:bg-indigo-600\" type=\"submit\">Submit</button></div></form></div><div class=\"w-full md:w-1/2 flex justify-center\"><img src=\"/static/img/dicoo.png\" alt=\"Monitoring\"></div></div></section><script defer>\n            if ({ data.IsMessageSent }) {\n                alert(\"Message sent. We will get back to you soon.\")\n            }\n        </script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout(data).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
