services:
  web:
    image: reaper99/heavy-metal-notifier:v1.0.0
    container_name: heavy-metal-notifier
    restart: unless-stopped
    environment:
      - HOST_URL=https://metal.musicavis.ca
      - IS_PROD=true
      - SMTP_USERNAME=my@gmail.com
      - SMTP_PASSWORD="my app pass word"
