// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/reaper47/heavy-metal-notifier/internal/templates"
)

func TOSPage(data templates.Data) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layout(tos(data), data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func tos(data templates.Data) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"col-span-12 py-20\" style=\"background: linear-gradient(90deg, #D73737 0%, #3D3D3D 100%)\"></section><section class=\"col-span-12 container mx-auto px-6 p-10\"><div class=\"flex items-center flex-wrap mb-20\"><div class=\"w-full md:w-1/2\"><h4 class=\"text-3xl text-gray-800 font-bold mb-3\">Terms of Service\r</h4><p class=\"text-gray-600 mb-8\">Please read through our Terms of Service carefully before using our service.\r</p><h5 class=\"text-3xl text-gray-800 font-bold mb-3\">Scope of Service\r</h5><p class=\"text-gray-600 mb-8\">The website, Heavy Metal Releases Notifier, offers a service to automatically notify you of new\r heavy metal album releases throughout the current year. The user will be notified by email on\r new releases.\r</p><h5 class=\"text-3xl text-gray-800 font-bold mb-3\">Intellectual Property Rights\r</h5><p class=\"text-gray-600 mb-8\">The user is free to use this program ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(`for`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `tos.templ`, Line: 36, Col: 63}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" whatever reason because it is licensed under the MIT license.\r The user acknowledges that any content submitted or transferred to the website becomes the property of\r the one who hosts an instance of Heavy Metal Releases Notifier and may be used ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(`for`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `tos.templ`, Line: 38, Col: 105}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" any lawful purpose\r without compensation to the user. Heavy Metal Releases Notifier reserves the right to refuse service\r to any user ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(`for`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `tos.templ`, Line: 40, Col: 38}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" any reason at any time. The images are from <a href=\"https://pixabay.com\">Pixabay</a> and <a href=\"https://commons.wikimedia.org/wiki/Main_Page\">Wikimedia Commons</a>.\r</p><h5 class=\"text-3xl text-gray-800 font-bold mb-3\">User Conduct\r</h5><p class=\"text-gray-600 mb-8\">The user must respect basic human interactions when using the website or contacting support.\r This includes not using offensive language, making personal attacks, or engaging in any behavior\r that may be considered harassing or threatening. Heavy Metal Releases Notifier reserves the right to\r terminate the user's account ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(`if`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `tos.templ`, Line: 51, Col: 54}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" they violate these terms of conduct.\r</p><h5 class=\"text-3xl text-gray-800 font-bold mb-3\">Disclaimer of Warranties\r</h5><p class=\"text-gray-600 mb-8\">The website is provided on an \"as is\" and \"as available\" basis. Heavy Metal Releases Notifier makes no\r representations or warranties of any kind, express or implied, as to the operation of the website\r or the information, content, materials, or products included on the website. The user acknowledges\r that their use of the website is at their own risk. Heavy Metal Releases Notifier does not warrant that\r the website will be uninterrupted or error-free, and Heavy Metal Releases Notifier will not be liable\r ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(`for`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `tos.templ`, Line: 63, Col: 26}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" any interruptions or errors.\r</p><h5 class=\"text-3xl text-gray-800 font-bold mb-3\">Limitation of Liability\r</h5><p class=\"text-gray-600 mb-8\">Heavy Metal Releases Notifier is not responsible ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(`for`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `tos.templ`, Line: 70, Col: 75}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" any missed headbanging to the newest heavy metal\r releases. The user acknowledges that Heavy Metal Releases Notifier will not be liable for any damages\r of any kind arising from the use of the website and from excessive headbanging.\r</p><h5 class=\"text-3xl text-gray-800 font-bold mb-3\">Disputes\r</h5><p class=\"text-gray-600 mb-8\">Any dispute arising from the use of this website or its services will be governed by the laws of\r the jurisdiction in which Heavy Metal Releases Notifier is located. The user agrees to submit to the\r jurisdiction of the courts in that jurisdiction ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(`for`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `tos.templ`, Line: 81, Col: 74}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" resolution of any such dispute.\r</p><h5 class=\"text-3xl text-gray-800 font-bold mb-3\">Changes to the TOS\r</h5><p class=\"text-gray-600 mb-8\">Heavy Metal Releases Notifier reserves the right to modify these terms of service at any time. Any changes\r will be communicated to users through the website. The user's continued use of the website following\r any changes to the TOS constitutes acceptance of those changes.\r</p><h5 class=\"text-3xl text-gray-800 font-bold mb-3\">Governing Law\r</h5><p class=\"text-gray-600 mb-8\">This Terms of Service agreement and the relationship between the user and Heavy Metal Releases Notifier\r shall be governed by and construed in accordance with the laws of heavy metal. The user\r agrees to submit to the jurisdiction of the courts located in Heaven ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(`for`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `tos.templ`, Line: 99, Col: 95}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" any and all\r disputes arising from or related to the use of the website and its services.\r</p><h5 class=\"text-3xl text-gray-800 font-bold mb-3\">Contact Information\r</h5><p class=\"text-gray-600 mb-8\">If you have any questions or concerns regarding these Terms of Service agreement, please contact\r Heavy Metal Releases Notifier at\r <a href=\"mailto:metal.releases.666@gmail.com\" target=\"_blank\" class=\"text-blue-500 hover:text-blue-600\" aria-label=\"Email metal.releases.666@gmail.com\">metal.releases.666@gmail.com\r</a>.\r</p></div><div class=\"w-full md:w-1/2\"><img src=\"/static/img/dicoo.png\" alt=\"Monitoring\"></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
