name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install templ
      run: go install github.com/a-h/templ/cmd/templ@latest

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.7.0
      with:
        version: latest
        args: --timeout 10m

    - name: Build and test
      run: task test
