name: Nightly

on:
  #schedule:
  #  - cron: "0 1 * * *"
  pull_request

permissions:
  contents: read
  packages: write

jobs:
  commits:
    name: Commits
    runs-on: ubuntu-latest
    outputs:
      numCommits: ${{ steps.numCommits.outputs.commits }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get new commits
        id: numCommits
        run: echo "commits=$(git log --oneline --since '24 hours ago' | wc -l)" >> "$GITHUB_OUTPUT"

  binaries:
    timeout-minutes: 60
    needs: commits
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
#          - build: linux
#            os: ubuntu-latest
#            target: x86_64-unknown-linux-musl
#            artifact: metal-nightly-x86_64-unknown-linux-musl
#
#          - build: linux
#            os: ubuntu-latest
#            target: x86_64-unknown-linux-gnu
#            artifact: metal-nightly-x86_64-unknown-linux-gnu
#
#          - build: linux
#            os: ubuntu-latest
#            target: aarch64-unknown-linux-gnu
#            artifact: metal-nightly-aarch64-unknown-linux-gnu
#
#          - build: linux
#            os: ubuntu-latest
#            target: armv7-unknown-linux-gnueabihf
#            artifact: metal-nightly-armv7-unknown-linux-gnueabihf
#
#          - build: macos
#            os: macos-latest
#            target: x86_64-apple-darwin
#            artifact: metal-nightly-x86_64-apple-darwin
#
#          - build: macos
#            os: macos-latest
#            target: aarch64-apple-darwin
#            artifact: metal-nightly-aarch64-apple-darwin

          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: metal-nightly-x86_64-pc-windows-msvc

          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-gnu
            artifact: metal-nightly-x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - if: ${{ runner.os == 'Linux' }}
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: |
            musl-tools 
            libsqlite3-dev 
            gcc-13 
            gcc-13-aarch64-linux-gnu 
            gcc-aarch64-linux-gnu 
            aarch64-linux-gnu-gcc 
            gcc-arm-linux-gnueabihf
          version: 1.0

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: npm


      - name: Build Archive
        shell: bash
        run: |
          OUTPUT_NAME="heavy-metal-notifier"
          if [ ${{ matrix.os }} = "windows-latest" ]; then
            OUTPUT_NAME="heavy-metal-notifier.exe"
          fi
          
          OUTPUT_PATH=staging-directory
          mkdir -p $OUTPUT_PATH
          
          PREPARE_DIR=/tmp/heavy-metal-notifier/${{ matrix.artifact }}
          mkdir -p $PREPARE_DIR
          
          cargo build --target ${{ matrix.target }} --release
          cp target/${{ matrix.target }}/release/heavy-metal-notifier $PREPARE_DIR/$OUTPUT_NAME
          cp ./deploy/.env.example $PREPARE_DIR/.env
          cp LICENSE $PREPARE_DIR
          
          if [ ${{ matrix.os }} = "windows-latest" ]; then
            CURRENT_DIR=$(pwd)
            cd $PREPARE_DIR
            7z a $CURRENT_DIR/$OUTPUT_PATH/${{ matrix.artifact }}.zip *
            sha256sum $CURRENT_DIR/$OUTPUT_PATH/${{ matrix.artifact }}.zip > $CURRENT_DIR/$OUTPUT_PATH/${{ matrix.artifact }}.zip.sha256
          elif [ ${{ matrix.os }} = "macos-latest" ]; then
            CURRENT_DIR=$(pwd)
            cd $PREPARE_DIR
            echo $CURRENT_DIR
            echo $PREPARE_DIR
            tar -czvvf $CURRENT_DIR/$OUTPUT_PATH/${{ matrix.artifact }}.tgz *
            GENERATED_SHA_256=$(shasum -a 256 $CURRENT_DIR/$OUTPUT_PATH/${{ matrix.artifact }}.tgz | awk '{print $1}')
            echo $GENERATED_SHA_256 > $CURRENT_DIR/$OUTPUT_PATH/${{ matrix.artifact }}.tgz.sha256
          else
            CURRENT_DIR=$(pwd)
            cd $PREPARE_DIR
            tar -czvvf $CURRENT_DIR/$OUTPUT_PATH/${{ matrix.artifact }}.tgz *
            GENERATED_SHA_256=$(shasum -a 256 $CURRENT_DIR/$OUTPUT_PATH/${{ matrix.artifact }}.tgz | awk '{print $1}')
            echo $GENERATED_SHA_256 > $CURRENT_DIR/$OUTPUT_PATH/${{ matrix.artifact }}.tgz.sha256    
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: staging-directory
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: binaries

    steps:
      - uses: actions/checkout@v4

      - name: Download Nightly Build x86_64-unknown-linux-musl
        uses: actions/download-artifact@v4
        with:
          name: metal-nightly-x86_64-unknown-linux-musl
          path: downloads

      - name: Download Nightly Build x86_64-unknown-linux-gnu
        uses: actions/download-artifact@v4
        with:
          name: metal-nightly-x86_64-unknown-linux-gnu
          path: downloads

      - name: Download Nightly Build aarch64-unknown-linux-gnu
        uses: actions/download-artifact@v4
        with:
          name: metal-nightly-aarch64-unknown-linux-gnu
          path: downloads

      - name: Download Nightly Build armv7-unknown-linux-gnueabihf
        uses: actions/download-artifact@v4
        with:
          name: metal-nightly-armv7-unknown-linux-gnueabihf
          path: downloads

      - name: Download Nightly Build x86_64-apple-darwin
        uses: actions/download-artifact@v4
        with:
          name: metal-nightly-x86_64-apple-darwin
          path: downloads

      - name: Download Nightly Build aarch64-apple-darwin
        uses: actions/download-artifact@v4
        with:
          name: metal-nightly-aarch64-apple-darwin
          path: downloads

      - name: Download Nightly Build x86_64-pc-windows-msvc
        uses: actions/download-artifact@v4
        with:
          name: metal-nightly-x86_64-pc-windows-msvc
          path: downloads

      - name: Download Nightly Build x86_64-pc-windows-gnu
        uses: actions/download-artifact@v4
        with:
          name: metal-nightly-x86_64-pc-windows-gnu
          path: downloads

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          automatic_release_tag: nightly
          prerelease: false
          title: "Nightly Build"
          files: |
            downloads/metal-nightly-x86_64-unknown-linux-musl.tgz
            downloads/metal-nightly-x86_64-unknown-linux-musl.tgz.sha256
            downloads/metal-nightly-x86_64-unknown-linux-gnu.tgz
            downloads/metal-nightly-x86_64-unknown-linux-gnu.tgz.sha256
            downloads/metal-nightly-aarch64-unknown-linux-gnu.tgz
            downloads/metal-nightly-aarch64-unknown-linux-gnu.tgz.sha256
            downloads/metal-nightly-armv7-unknown-linux-gnueabihf.tgz
            downloads/metal-nightly-armv7-unknown-linux-gnueabihf.tgz.sha256
            downloads/metal-nightly-aarch64-unknown-linux-gnu.tgz
            downloads/metal-nightly-aarch64-unknown-linux-gnu.tgz.sha256
            downloads/metal-nightly-x86_64-apple-darwin.tgz
            downloads/metal-nightly-x86_64-apple-darwin.tgz.sha256
            downloads/metal-nightly-aarch64-apple-darwin.tgz
            downloads/metal-nightly-aarch64-apple-darwin.tgz.sha256
            downloads/metal-nightly-x86_64-pc-windows-msvc.zip
            downloads/metal-nightly-x86_64-pc-windows-msvc.tgz.sha256
            downloads/metal-nightly-x86_64-pc-windows-gnu.zip
            downloads/metal-nightly-x86_64-pc-windows-gnu.zip.sha256
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    needs: release

    steps:
      - name: Set vars
        id: vars
        run: |
          echo "VERSION=nightly" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            reaper99/heavy-metal-notifier:${{ steps.vars.outputs.VERSION }} 
            ghcr.io/${{ github.repository_owner }}/heavy-metal-notifier:${{ steps.vars.outputs.VERSION }}
