name: Nightly

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  commits:
    name: Commits
    runs-on: ubuntu-latest
    outputs:
      numCommits: ${{ steps.numCommits.outputs.commits }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get new commits
        id: numCommits
        run: echo "commits=$(git log --oneline --since '24 hours ago' | wc -l)" >> "$GITHUB_OUTPUT"
  
  nightly:
    name: Nightly
    runs-on: ubuntu-latest
    needs: commits
    if: ${{ needs.commits.outputs.numCommits > 0 }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SQLite3 dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: stable
      
      - name: Compile (rust-analyzer)
        run: cargo build

      - name: Test
        run: cargo test -- --nocapture --quiet

      - name: Build Docker image
        run: docker build -t reaper99/heavy-metal-notifier:nightly . -f ./deploy/Dockerfile

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multi-platform Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t reaper99/heavy-metal-notifier:nightly \
            --push .
