name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: quartx-analytics/ghcr-cleaner@v1
      with:
        owner-type: org # or user
        token: ${{ secrets.GH_TOKEN }}
        delete-untagged: true

    - name: Install SQLite3 dependencies
      run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: stable

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test -- --nocapture --quiet
